### PR TITLE
Add primary color + change TGX template to use it

### PR DESCRIPTION
**Pull request by heokhe**

### CODE REVIEW

**Comment by vrumger** [comment]
I think it would make a bit more sense if the primary color was second (after the background). 🤔

**Comment by heokhe** [comment]
> I think it would make a bit more sense if the primary color was second (after the background).

:thinking:
I didn't think about the order at the time of coding. Change it as you want.

**Comment by vrumger** [comment]
Okay, I'll do it later when I get a chance.

**Comment by heokhe** [comment]
Could you tell me whenever the code is deployed? I need new themes :sweat_smile:

**Comment by vrumger** [comment]
It's already deployed. ;)

**Comment by heokhe** [comment]
:confetti_ball::tada:

**Pull request merged**
